### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by sandeesh**
Updated repo link and removed wrong build information badge.
Advise to setup travis build on the main repo and add the correct badge.

### CODE REVIEW

**Comment by realazizk** [comment]
@SandeeshS hey, yep I didn't pay attention to the travis-ci image link, setting up an independent travis-ci build looks like a good idea

https://github.com/mohamed-aziz/realworld-flask/commit/9b0cfb6d057ceab18f33a3203548c54e1caf02cc

**Comment by sandeesh** [comment]
@mohamed-aziz is this getting merged? the instructions still point to the old repo.

**Comment by realazizk** [comment]
@SandeeshS I don't know, I can't merge on this repo.

**Comment by sandeesh** [comment]
@mohamed-aziz you should've been given admin access to this repo. @EricSimons can you check this out? @mohamed-aziz  is the author of this repo, but has limited/no access.

**Comment by EricSimons** [comment]
@SandeeshS I actually added @mohamed-aziz a few weeks ago when I created this repo, github says his invite is still pending (i.e. @mohamed-aziz you need to accept the invitation :)

screen shot 2017-06-06 at 1 57 45 pm

**Comment by realazizk** [comment]
My bad, @EricSimons sent the invitation three weeks ago, I didn't pay attention.

**Comment by EricSimons** [comment]
No sweat :)                                                                                                                                                                           From: notifications@github.comSent: June 6, 2017 2:02 PMTo: flask-realworld-example-app@noreply.github.comReply-to: reply@reply.github.comCc: eric@esft.com; mention@noreply.github.comSubject: Re: [gothinkster/flask-realworld-example-app] Update README.rst (#1)  My bad, @EricSimons sent the invitation three weeks ago, I didn't pay attention.

**Pull request merged**
